### ISSUE TITLE
weighted record howto?

### ISSUE THREAD

**Issue by sbagmeijer** [chef-cookbooks/route53#100]
We try to created a weighted record according to route53 if all the weighted entries are 0 then it loadbalances it equally.

so we already have 2 entries like this:
test.example.com CNAME work.example.com WEIGHT 0 ID BLABLA1
test.example.com CNAME work.example.com WIGHT 0 ID BLABLA2

Now I try to automate this in opsworks with this module and I use the following:

```
include_recipe "route53"

instance_info = search(:aws_opsworks_instance, "self:true").first

route53_record "create a record" do
  name  "test.example.com"
  value "work.example.com,"
  type  "CNAME"
    ttl 300
  weight "0"
  set_identifier "#{instance_info[:hostname]}"
  zone_id               "xxxx"
  aws_access_key_id     "xxxxx"
  aws_secret_access_key "xxxxx"
  overwrite true
  action :create
end
```

But we keep getting the following error:

```
[2016-10-14T12:52:40+00:00] ERROR: Error with UPSERTrequest: {:hosted_zone_id=>"/hostedzone/XXXXXXX", :change_batch=>{:comment=>"Chef Route53 Resource: test.example.com.", :changes=>[{:action=>"UPSERT", :resource_record_set=>{:name=>"test.example.com.", :type=>"CNAME", :ttl=>300, :resource_records=>[{:value=>"work.example.com"}]}}]}} ::: 
[2016-10-14T12:52:40+00:00] ERROR: RRSet with DNS name test.example.com., type CNAME cannot be created as other RRSets exist with the same name and type.
```

Do you see what we do wrong?

**Comment by sbagmeijer** [comment]
My colleague helped out and created a small fix so the weight will work we tested this also to make sure it works.

However we both think that the way this is done currently to detect "geo_location" and "weight" is not very nice.

Perhaps a better alternative is to add an additional option such as "routing_policy" and then you should be able to select:
simple
weighted
latency
failover
geolocation

and then it should select the required things route 53 needs.

**Comment by tas50** [comment]
The route53_record resource in this cookbook has been merged into the aws cookbook itself and improved quite a bit. There's also been a new aws_route53_zone resource added for creating / deleting zones. At this point in time we're deprecating this cookbook in favor of the aws cookbook. If you're still having this issue feel free to open it up in the aws cookbook.
