### ISSUE TITLE
Unable to create records when an IAM role is attached

### ISSUE THREAD

**Issue by catalinvr** [chef-cookbooks/route53#105]
### Cookbook version
1.1.0

### Chef-client version
12.17.44

### Platform Details
Ubuntu 14.04 on AWS

### Scenario:
Chef-client is unable to create a route53 record with provided credentials when an instance have attached an IAM role on it.

### Steps to Reproduce:
1. Create an instance into a private subnet with an IAM role attached. IAM Role can read file from S3
2. Create a new IAM user/role that is able to a Route53 record. Download credentials.
3. Create a wrapper cookbook to create a record

`aws_creds = {...}`
`route53_record "node['fqdn]" do`
`      value node['ec2']['local_ipv4']`
`      type  "A"`
`      zone_id               node[:wrapper_route53][:zone_id]`
`      aws_access_key_id     aws_creds["aws_access_key_id"]`
`      aws_secret_access_key aws_creds["aws_secret_access_key"]`
`      ttl                   node[:wrapper_route53][:ttl]`
`      action :create`
`end`

4. Add the wrapper cookbook into your runlist
5. Run chef client

### Expected Result:
Create a new record in Route53

### Actual Result:
`* route53_record[test-cata.mydomain.com] action create`
`================================================================================`
`    Error executing action `create` on resource 'route53_record[test-cata.mydomain.com]'`
`================================================================================`
`    Aws::Route53::Errors::AccessDenied`
`    ----------------------------------`
`    User: arn:aws:iam::123456789909:user/read_S3 is not authorized to access this resource`
`    Cookbook Trace:`
`    ---------------`
`    /var/chef/cache/cookbooks/route53/providers/record.rb:114:in 'current_resource_record_set'`
`    /var/chef/cache/cookbooks/route53/providers/record.rb:167:in 'block in class_from_file'`

**Comment by tas50** [comment]
Thanks for the fix
