### ISSUE TITLE
route53_record fails to delete A record

### ISSUE THREAD

**Issue by mgoldsborough** [chef-cookbooks/route53#109]
### Cookbook version

1.2.1

### Chef-client version

12.13.37

### Platform Details

Ubuntu 16.04 LTS, AWS OpsWorks

### Scenario:

Error when deleting Route53 record.

### Steps to Reproduce:

I'm trying to clean up some DNS via:

```
route53_record "deleting internal record" do
  name  instance['hostname'] + node['internal_dns']['domain_name']
  zone_id node['internal_dns']['private_zone_id']
  type  "A"
  action :delete
end
```

### Expected Result:

The A record should be deleted.

### Actual Result:

The DNS record is not removed and an error in the logs. Looks like an underlying API call is failing:

```
[2017-01-27T18:33:29+00:00] ERROR: Error with DELETErequest: {:hosted_zone_id=>"/hostedzone/Z38DPBBF3IW9B0", :change_batch=>{:comment=>"Chef Route53 Resource: french-toast.test-domain.", :changes=>[{:action=>"DELETE", :resource_record_set=>{:name=>"french-toast.test-domain.", :type=>"A", :ttl=>3600, :resource_records=>[]}}]}} ::: 
[2017-01-27T18:33:29+00:00] ERROR: Unexpected list element termination
```

**Comment by VenkataMutyala** [comment]
I was running into a similar issue. i found that to delete a record I had to do the following:

> route53_record "create a record" do
>   name  'venkata.example.com'
>   value 'test'
>   type  "A"
>   ttl   60
>   zone_id   'ZJHSKJD891KKQ'
>   fail_on_error true
>   action :delete
> end
> 

It seems like the name, value, type, and ttl attributes must be exactly the same values as what's active.

I hope this helps as a work around.

**Comment by mgoldsborough** [comment]
@VenkataMutyala that seemed to do the trick. Seems odd you should have to include the value and the ttl. Shouldn't just providing the name be sufficient?

**Comment by iennae** [comment]
Hey folks, 

This looks like you've discovered a limitation of the aws sdk that is used for the delete action. Could you confirm that I'm understanding this correctly? Thanks!

**Comment by tas50** [comment]
The route53_record resource in this cookbook has been merged into the aws cookbook itself and improved quite a bit. There's also been a new aws_route53_zone resource added for creating / deleting zones. At this point in time we're deprecating this cookbook in favor of the aws cookbook. If you're still having this issue feel free to open it up in the aws cookbook.
