### ISSUE TITLE
Aws::Route53::Errors::Throttling still happening

### ISSUE THREAD

**Issue by ls-jftheroux** [chef-cookbooks/route53#110]
### Cookbook version
1.2.1

### Chef-client version
12.14.77

### Platform Details
Centos 7 and Ubuntu 16.04

### Scenario:
We're able to trigger the rate limit error easily. We have test-kitchen setups that test full clusters, and some of these setup do deploy a lot of instances in AWS. They end up hitting that limit frequently.

### Expected Result:
The cookbook handling rate limits errors by the Route 53 API. It should then sleep for 1 second, try, if still fails, sleep for last_sleep * 2, retry, etc.

### Actual Result:
Chef run fails.

I'm working on a patch. If you guys are interested, I'll submit it. Open to suggetions on behavior.

**Comment by iennae** [comment]
@ls-jftheroux Could you provide more information. Definitely interested in hearing more about this issue and what you think might help.

**Comment by lucasreed** [comment]
@ls-jftheroux Have you attempted using the chef built-in properties `retries` and `retry_delay` when you declare your route53_record resource in a recipe? I haven't been able to test this myself but it I believe it should work in this case.

https://docs.chef.io/resource_common.html#properties

**Comment by ls-jftheroux** [comment]
Well, we ended up writing some custom code and stopped using the resource itself since I opened this issue. We needed more in the end than record creation. We wrote a lib that does a few things for us with R53.

**Comment by iennae** [comment]
Ahh. Thanks for the update @ls-jftheroux. I'm going to go ahead and close this.
