### ISSUE TITLE
Interaction with the apt::default recipe

### ISSUE THREAD

**Issue by rberger** [chef-cookbooks/route53#53]
This one took a while to figure out (at least for me).

I had the `recipe[apt::default]` as the first thing in my run_list. Everything was working nice. Then included the route53 cookbook in my base recipe and all of the sudden things were failing for new nodes due to some packages failing during install due to apt not being up to date. 

I.E. there were packages being installed before the apt::default recipe being run.

I eventually tracked it down to the fact that route53 sets `node['build_essential']['compiletime'] = true` which means it will install build_install (and it looks like some other stuff) during compiletime, which is before the normal apt::default is run.

The fix (at least for me) was to do the same thing for apt. I had to override `apt[:compile_time_update]` to be `true` and that fixed that issue.
Might want to add this to the README.

**Comment by tas50** [comment]
Fog has been replaced with the aws-sdk so this is no longer a valid issue
