### ISSUE TITLE
Feature: Allow to create Weighted Resource Record Sets

### ISSUE THREAD

**Issue by chilicat** [chef-cookbooks/route53#59]
Allow to create Weighted Resource Record Sets as shown here:

http://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets_Examples.html

**Comment by slyness** [comment]
We are working on merging #12 which will help to address this issue.

**Comment by pmacdougall** [comment]
I see #12 is merged but I cannot create weighted record sets using the current master branch (816318e).  No errors, but last record in the set seems to win.

Is this still a work in progress?

**Comment by sbagmeijer** [comment]
We had the same problem, please have a look at #100

**Comment by tas50** [comment]
The route53_record resource in this cookbook has been merged into the aws cookbook itself and improved quite a bit. There's also been a new aws_route53_zone resource added for creating / deleting zones. At this point in time we're deprecating this cookbook in favor of the aws cookbook. If you're still having this issue feel free to open it up in the aws cookbook.
