### ISSUE TITLE
chef-client 11.18.0 issue with ssl 

### ISSUE THREAD

**Issue by michaelmaring** [chef-cookbooks/route53#61]
Recipe: internal-base::route53
  * route53_record[d-internal-deploy-7699139a.internal.com] action create

    ================================================================================
    Error executing action `create` on resource 'route53_record[d-internal-deploy-7699139a.internal.com]'
    ================================================================================

    Excon::Errors::SocketError
    --------------------------
    Unable to verify certificate, please set `Excon.defaults[:ssl_ca_path] = path_to_certs`, `ENV['SSL_CERT_DIR'] = path_to_certs`, `Excon.defaults[:ssl_ca_file] = path_to_file`, `ENV['SSL_CERT_FILE'] = path_to_file`, `Excon.defaults[:ssl_verify_callback] = callback` (see OpenSSL::SSL::SSLContext#verify_callback), or `Excon.defaults[:ssl_verify_peer] = false` (less secure).

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/route53/providers/record.rb:53:in `zone'
    /var/chef/cache/cookbooks/route53/providers/record.rb:69:in `record'
    /var/chef/cache/cookbooks/route53/providers/record.rb:114:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/internal-base/recipes/route53.rb

      7: route53_record "create a record" do
      8:   name  		full_nodename
      9:   value 		node['ipaddress']
     10:   type  		"A"
     11:   zone_id               node['route53']['zone_id']
     12:   aws_access_key_id     aws_creds["aws_access_key_id"]
     13:   aws_secret_access_key aws_creds["aws_secret_access_key"]
     14:   ttl                   600
     15:   overwrite 		true
     16:   action :create
     17: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/internal-base/recipes/route53.rb:7:in `from_file'

    route53_record("d-internal-deploy-7699139a.internal.com") do
      action [:create]
      retries 0
      retry_delay 2
      guard_interpreter :default
      cookbook_name "internal-base"
      recipe_name "route53"
      value "10.3.7.14"
      type "A"
      zone_id "********"
      aws_access_key_id "********""
      aws_secret_access_key "********"
      ttl 600
      overwrite true
    end

Running handlers:
  - Chef::Handler::Slack
Running handlers complete
Chef Client failed. 7 resources updated in 13.479688753 seconds
(21:55:59) â—‹ development â—‹ [root@d-internal-deploy-7699139a.internal.com] ~
â†’ cat /var/chef/cache/chef-stacktrace.out
Generated at 2015-01-18 21:55:58 +0000
Excon::Errors::SocketError: route53_record[d-internal-deploy-7699139a.internal.com] (internal-base::route53 line 7) had an error: Excon::Errors::SocketError: Unable to verify certificate, please set `Excon.defaults[:ssl_ca_path] = path_to_certs`, `ENV['SSL_CERT_DIR'] = path_to_certs`, `Excon.defaults[:ssl_ca_file] = path_to_file`, `ENV['SSL_CERT_FILE'] = path_to_file`, `Excon.defaults[:ssl_verify_callback] = callback` (see OpenSSL::SSL::SSLContext#verify_callback), or `Excon.defaults[:ssl_verify_peer] = false` (less secure).
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.42.1/lib/excon/ssl_socket.rb:121:in `connect_nonblock'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.42.1/lib/excon/ssl_socket.rb:121:in `block in initialize'
/opt/chef/embedded/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.42.1/lib/excon/ssl_socket.rb:117:in `initialize'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.42.1/lib/excon/connection.rb:380:in `new'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.42.1/lib/excon/connection.rb:380:in `socket'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.42.1/lib/excon/connection.rb:105:in `request_call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.42.1/lib/excon/middlewares/mock.rb:47:in `request_call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.42.1/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.42.1/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.42.1/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.42.1/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.42.1/lib/excon/connection.rb:232:in `request'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/fog-xml-0.1.1/lib/fog/xml/sax_parser_connection.rb:37:in `request'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/fog-xml-0.1.1/lib/fog/xml/connection.rb:7:in `request'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/fog-1.24.0/lib/fog/aws/dns.rb:144:in `_request'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/fog-1.24.0/lib/fog/aws/dns.rb:139:in `request'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/fog-1.24.0/lib/fog/aws/requests/dns/get_hosted_zone.rb:33:in `get_hosted_zone'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/fog-1.24.0/lib/fog/aws/models/dns/zones.rb:21:in `get'
/var/chef/cache/cookbooks/route53/providers/record.rb:53:in `zone'
/var/chef/cache/cookbooks/route53/providers/record.rb:69:in `record'
/var/chef/cache/cookbooks/route53/providers/record.rb:114:in `block in class_from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/provider/lwrp_base.rb:138:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/provider/lwrp_base.rb:138:in `block in action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/provider.rb:125:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource.rb:648:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource_collection.rb:96:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/client.rb:345:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/client.rb:431:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/client.rb:213:in `block in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/client.rb:207:in `fork'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/client.rb:207:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/application/client.rb:338:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/application/client.rb:327:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/application/client.rb:327:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/application.rb:55:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:23:in `load'
/usr/bin/chef-client:23:in `<main>'(21:56:15) â—‹ development â—‹ [root@d-internal-deploy-7699139a.internal.com] ~
â†’

**Comment by slyness** [comment]
We will need to try and reproduce this error. At first glance it might be related to the chef-client SSL environment. This post may provide some insight: https://www.chef.io/blog/2013/10/31/ssl-certificate-validation-in-chef/ 

It will be helpful to know more information about the context in which you're running Chef. Are you using the omnibus installer, etc...

**Comment by Azrael808** [comment]
Hey @slyness - I am able to replicate the issue reliably by following these steps:

1. Use the `knife-server` and `knife-ec2` plugins to spin up a new Chef Server (11.18.0) in EC2; using CentOS 6 as my base.
2. Upload my cookbooks, data bags, etc.
3. Use `knife ec2 server create` specifying a role/recipe that includes a call to `route53_record`, again, using CentOS 6.
4. When the chef run hits that point, the error mentioned above is given.

I can fix the issue by setting an environment variable as suggested in the error and, in fact, I've incorporated this fix into my recipe with a `ruby_block` resource that configures the `SSL_CERT_FILE` variable before calling the `route53_record` resource.

**Comment by scottbessler** [comment]
I'm having this issue as well with Chef 11.18.0 with Ubuntu 14.04

**Comment by slyness** [comment]
@scottbessler thank you. I will test and get this merged and released as soon as I can.

**Comment by slyness** [comment]
Can you please open a PR to the develop branch with your commit?

**Comment by tas50** [comment]
This cookbook requires Chef 12 or later now. If you're seeing similar issues on Chef 12+ feel free to open this back up
