### ISSUE TITLE
Unable to find documentation for `alias_target`

### ISSUE THREAD

**Issue by Azrael808** [chef-cookbooks/route53#64]
I hope this isn't a stupid question, but I'm attempting to use this cookbook to manage some alias records in Route53 and I can't see what format the `alias_target` hash takes.

I'd be happy to fork and update the Readme if someone could provide me with an example!

**Comment by hexedpackets** [comment]
It's being passed to fog so it needs to match the format fog expects. I found this example:

https://github.com/fog/fog-aws/blob/916351a3532e80a0318e766ec12bb87fa2348350/tests/requests/dns/dns_tests.rb#L179-L183

**Comment by iennae** [comment]
Thanks for reporting this issue. The documentation has been updated in the README.
