### ISSUE TITLE
Feature: Allow creating A records with multiple addressess

### ISSUE THREAD

**Issue by zeridon** [chef-cookbooks/route53#68]
It would be nice if an A record with multiple values could be created (for roundrobin loadbalancing).

**Comment by uditjh** [comment]
Its already available assuming we are noth talking about the same thing. You have to pass the value as an array.  example: value  ["10.1.1.1", "10.2.2.2.", "10.3.3.3"]

**Comment by iennae** [comment]
As mentioned earlier, the value parameter can take an array as used in an example.
