### ISSUE TITLE
fog-aws 0.7.0 causes errors

### ISSUE THREAD

**Issue by opsline-radek** [chef-cookbooks/route53#78]
The newest fog-aws 0.7.0 causes an error when creating records.

```
  * route53_record[...] action create

    ================================================================================
    Error executing action `create` on resource 'route53_record[...]'
    ================================================================================

    Fog::DNS::AWS::Error
    --------------------
    InvalidInput => Invalid XML ; cvc-elt.1: Cannot find the declaration of element 'ChangeResourceRecordSetsRequest'.

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/route53/providers/record.rb:87:in `create'
    /var/chef/cache/cookbooks/route53/providers/record.rb:115:in `block in class_from_file'
```

**Comment by opsline-radek** [comment]
Downgrading to fog-aws 0.6.0 fixes the issue.

**Comment by josacar** [comment]
Hope @slyness merge this https://github.com/hw-cookbooks/route53/pull/67 to avoid that situation

**Comment by StubbsPKS** [comment]
I am also experiencing this problem, but when using grep to look for fog-aws to change the version back down to 0.6.0 I don't see it in any files. Am I missing something or does this cookbook use fog and not aws-fog?

**Comment by josacar** [comment]
The cookbook still uses `fog` take a look to PR #67 , it's waiting on @slyness plate. I've forked it for months to get rid of that kind of errors

**Comment by markunsworth** [comment]
Anyone had any joy with the just released 0.7.1 release of fog-aws?

**Comment by opsline-radek** [comment]
I just tested PR #67. It worked well.

**Comment by josacar** [comment]
fog-aws 0.7.2 is out

**Comment by tas50** [comment]
Fog has been replaced with the aws-sdk so this is no longer a valid issue
