### ISSUE TITLE
A bunch of parallel chef-client runs causes Throttling => Rate exceeded

### ISSUE THREAD

**Issue by rberger** [chef-cookbooks/route53#79]
If one were to have a bunch of chef-client runs happening in parallel all trying to use the route53 plugin, it causes the Fog request and then the route53 recipe to fail.

Don't know if there would be a way to handle this with error handling and a backoff / retry?

Here's an example of the error:

```
Excon::Errors::BadRequest
-------------------------
Expected(200) <=> Actual(400 Bad Request)
excon.error.response
  :body          => "<?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"https://route53.amazonaws.com/doc/2013-04-01/\"><Error><Type>Sender</Type><Code>Throttling</Code><Message>Rate exceeded</Message></Error><RequestId>9113500b-5f12-11e5-b48e-9bb0009974f3</RequestId></ErrorResponse>"
  :headers       => {
    "Cneonction"       => "close"
    "Content-Length"   => "255"
    "Content-Type"     => "text/xml"
    "Date"             => "Sat, 18 Sep 2015 20:08:24 GMT"
    "x-amzn-RequestId" => "9112300b-5f12-11e5-b48e-9bb0009974f3"
  }
  :local_address => "172.31.32.255"
  :local_port    => 58717
  :reason_phrase => "Bad Request"
  :remote_ip     => "72.21.214.22"
  :status        => 400

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/route53/providers/record.rb:57:in `zone'
/var/chef/cache/cookbooks/route53/providers/record.rb:69:in `record'
/var/chef/cache/cookbooks/route53/providers/record.rb:114:in `block in class_from_file'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/mist_base/recipes/_route53.rb

 13: route53_record "create a record" do
 14:   name       fqdn
 15:   value      node[:ec2][:public_hostname]
 16:   type       "CNAME"
 17:   zone_id    cluster[:route53][:zone_id]
 18:   overwrite  true
 19:   action     :create
 20: end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/mist_base/recipes/_route53.rb:13:in `from_file'

route53_record("dashboard-000-staging.mistsys.net") do
  action [:create]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :route53_record
  cookbook_name "mist_base"
  recipe_name "_route53"
  value "ec2-52-0-56-073.compute-1.amazonaws.com"
  type "CNAME"
  zone_id "Z3C80NEKX49KXN"
  overwrite true
end
```

**Comment by palexvs** [comment]
I have the same issue with one chef-client, but that check a bunch of domains (>30)

**Comment by uditjh** [comment]
Amazon Route 53 allows only up to five requests per second per AWS account. The fix was to add a sleep of .2 seconds inside the resource block so no more than 5 requests are made per second.

**Comment by palexvs** [comment]
I added 0.3 sec. But sometimes it is not enough and I get exception

I wrote:
```
not_if 'sleep 0.3; false', timeout: 1
```
@uditjh do you have more beautiful variant?

route53 makes two request for one domain even if no modification is needed. It would be good if it will be optimized

**Comment by sean-kang** [comment]
I have the exact same problem in an environment that has more than 120 servers. Since this can be a common problem for AWS users, a fix needs be added to the cookbook.

**Comment by tas50** [comment]
I'm going to consider this as fixed as we can get it given that API limits still exist based on this. The aws-sdk is far more frugal with calls then fog so we should be able to scale this up further.

https://github.com/chef-cookbooks/route53/pull/96#issuecomment-248810759
