### ISSUE TITLE
Route53 records are case sensitive

### ISSUE THREAD

**Issue by AlexClineBB** [chef-cookbooks/route53#92]
We ran into a confusing situation while trying to create records using this cookbook. Creating a new record would begin, but ultimately fail because the record already existed. Trying to delete the record would fail because the record didn't exist.

We tracked the issue down to a difference in case between the record we were trying to create and what was ultimately created in Route53.

    foobar-R123.example.com gets created as foobar-r123.example.com
    deleting foobar-R123.example.com fails because the record doesn't exist in Fog's list

It may be useful to always `downcase` the name attribute within the record resource. At the minimum, a note should be added to the README that new records will be created with fully lowercase data, so cookbook users should downcase their hostname within their custom resource.

**Comment by tas50** [comment]
Fixed on master
