### ISSUE TITLE
Does it support waiting for the DNS name populated?

### ISSUE THREAD

**Issue by lioramilbaum** [chef-cookbooks/route53#97]
After setting the resource record,  I need to wait till the DNS name populated so I can use the dns name in the rest of my custom cookbook.

**Comment by tas50** [comment]
The route53_record resource in this cookbook has been merged into the aws cookbook itself and improved quite a bit. There's also been a new aws_route53_zone resource added for creating / deleting zones. At this point in time we're deprecating this cookbook in favor of the aws cookbook. If you're still having this issue feel free to open it up in the aws cookbook.
